name: Linters

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip pre-commit
      - name: Run linters
        run: |
          pre-commit run --hook-stage=manual --all-files
  docs:
    name: Docs Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e ".[docs]"
      - name: Build docs
        run: |
          cd docs
          make html
